interface:
  background_img: background_jpg/b2.jpg
  lab_img: background_jpg/lab.png
  lab_screen_size: [600,350]
  refresh_sound_file: Sound_effect/refresh.wav
  upgrade_sound_file: Sound_effect/pay.wav
  save_sound_file: Sound_effect/ensure.wav
  error_sound_file: Sound_effect/error.wav
  exit_sound_file: Sound_effect/tip.wav
  screen_size: [165,220]
  lab_grid:
    background_color: "#2C3B35"
    button_color: "#448856"
    gold_icon: [15,45]
    gold_value: [40,47]
    diamond_icon: [115,45]
    diamond_value: [140,47]
    refresh_icon: [265,20]
    save_icon: [265,45]
    consume_grid: [[64,91],[64,139],[64,185],[64,231],[64,275],[64,323],[364,91],[364,139],[364,185],[364,231],[364,275],[364,323]]
    level_grid: [[192,75],[192,122],[192,169],[192,215],[192,261],[192,308],[495,75],[495,122],[495,169],[495,215],[495,261],[495,308]]
    upgrade_grid: [[224,78],[224,125],[224,173],[224,219],[224,264],[224,311],[529,78],[529,125],[529,173],[529,219],[529,264],[529,311]]

account:
  basic_setting: data/basic_setting.json
  refresh_sound_file: Sound_effect/refresh.wav
  upgrade_sound_file: Sound_effect/pay.wav
  save_sound_file: Sound_effect/ensure.wav
  error_sound_file: Sound_effect/error.wav
  exit_sound_file: Sound_effect/tip.wav
  initial_gold: 20000
  initial_diamond: 200

map:
  path: scenes/
  icon: icon/database.png
  canvas_size: [240,240]
  window_size: [360,280]
  background_size: [120,240]
  png:
    enemy: enemy_png/e5.png
    enemy_a: enemy_png/ea1.png
    enemy_ax: enemy_png/eax0.png 
    enemy_b: enemy_png/eb0.png
  size:
    enemy: [10,10]
    enemy_a: [20,20]
    enemy_ax: [30,30]
    enemy_b: [50,50]


main:
  background_img: background_jpg/b0.jpg
  screen_size: [240,320]
  welcome_pos: [10,8]
  welcome_color: "white"
  sign_pos: [10,250]
  account_pos: [115,55]
  account_icon: icon_png/account_interface.png
  normal_level_pos: [115,95]
  normal_level_icon: icon/database.png
  start_pos: [115,135]
  start_icon: icon_png/play_interface.png
  lab_pos: [115,175]
  lab_icon: icon_png/lab_interface.png
  net_pos: [115,215]
  net_icon: icon/internet.png
  button_size: [120,30]
  small_button_size: [25,25]
  help_icon: icon_png/help.png
  setting_icon: icon_png/setting.png
  skin_icon: icon/skin.png
  log_icon: icon/log.png
  log_pos: [130,290]
  skin_pos: [160,290]
  help_pos: [190,290]
  setting_pos: [220,290]
  help_color: "#2C3B35"
  setting_color: "#2C3B35"
  log_color: "#2C3B35"
  exit_sound_file: Sound_effect/tip.wav

help:
  background_img: background_jpg/b1.jpg
  screen_size: [240,320]
  button_bg_color: "#2C3B35"
  icon: icon_png/help.png
  help_operation_icon: icon_png/help_operation.png
  help_note_icon: icon_png/help_note.png
  help_operation_pos: [20,10]
  help_note_pos: [120,10]
  notebook_pos: [5,40]
  button_size: [60,25]
  small_button_size: [20,20]
  help_operation_txt: text/help_operation.txt
  help_note_txt: text/help_note.txt

set:
  sim_interval_list: [6,10,15,30] 
  screen_size: [200,150]
  steps: 20
  min_volume: 0
  max_volume: 1
  icon: icon/setting.png

skin:
  icon: icon/skin.png
  path: player_png
  png_data: [data/player_1.txt, data/player_2.txt, data/player_3.txt, data/player_4.txt]
  canvas_size: [100,220]
  
net:
  icon: icon/internet.png
  
log:
  icon: icon/log.png

setting:
  font: 'times_new_roman'
  sim_interval: 15  # (ms)
  volume: 1.0
  log: false
  screen_size: [480,600]
  status_bar_size: [480,30]
  gamescreen_size: [480,570]
  background_color: [0,0,0]
  bg_rollv: 18
  account_path: account/
  scene_path: data/demo_scene.json
  success_sound_file: Sound_effect/mission_accomplished.wav
  fail_sound_file: Sound_effect/mission_failed.wav
  default_ico: icon_png/fighter_icon.png
  main_ico: icon/main.png
  lab_ico: icon/engineering.png
  game_ico: icon/game.ico
  account_ico: icon/account.png
  fail_font_pos: [120,300]
  success_font_pos: [70,300]

player:
  missile:
    img: missile_png/missile0.png
    explode_sound_file: bomb_fire.wav
  mp3_path: Sound_effect/
  bullet_sound_file: fighter_bullet_fire.mp3
  missile_sound_file: fighter_missile_fire.mp3
  explode_sound_file: fighter_explode.mp3
  hit_sound_file: hurt2.wav


bullet:
  path: bullet_png/
  setting: data/bullet_info.csv

enemy:
  path: enemy_png/
  setting: data/enemy_info.csv
  explode_sound_file: Sound_effect/small_explode.wav
  big_explode_sound_file: Sound_effect/fighter_explode.mp3
  hurt_sound_file: Sound_effect/metal1.mp3
  diamond_sound_file: Sound_effect/diamond.wav


enemyfire:
  path: enemyfire_png/
  setting: data/enemyfire_info.csv
  type_a_sound_file: Sound_effect/laser_big_oneshot.mp3
  type_b_sound_file: Sound_effect/launch1.wav
  explode_sound_file: Sound_effect/bomb_fire.wav

enemy_path:
  path: path_josn

icon:
  path: icon_png/
  diamond: diamond.png
  gold: gold.png
  heart: heart.png
  lightning: lightning.png
  snow: snowflake.png
  warn: [warn1.png, warn2.png]
  cool: water_drop.png
  upgrade: upgrade.png
  refresh: refresh.png
  save: save.png
  pause: pause.png

